version: "3.7"

services:
  database_ignite_test:
    image: postgres
    container_name: database_ignite_test
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres


  app: 
    build: .
    container_name: fin_api
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app 
    links: 
      - database_ignite_test
    depends_on:
      - database_ignite_test

volumes:
  pgdata:
    driver: local